### ISSUE TITLE
imx7d-pico - run hello_world in uboot with UART 5/6 with picocom 

### ISSUE THREAD

**Issue by neuberfran** [mhanuel26/ada-ipstack#1]
Sorry to log into your github this way. I couldn't find you to contact elsewhere (free of charge).

I have several imx7d-pico and I really like this tiny board.

To advance the conversation I refer to this link:
https://github.com/TechNexion/freertos-tn/issues/1?fbclid=IwAR2rxlqGNV4B6Xv7OKEeXsL2fUrWrwuWPRQznZvRxtzs2i-KolDz8iaKOWw

Technexion doesn't answer me about this card because I discovered a defect in the usb-c of the same that burned the imx7d-pico SOM module.

My issue is

**fatload mmc 0:1 0x7F8000 hello_world.bin
** Reading file would overwrite reserved memory **
Failed to load 'hello_world.bin'**

PrintEnv Line 58

https://gist.github.com/neuberfran/23976e1dd7ea6554609f7fc72f8af285

too three importants files in Yocto imx7d-pico/Hardknott configuration:

pico-imx7.conf
https://gist.github.com/neuberfran/2fd1c03465fb343a09f916eb4f494991

and imx7d-pico-pi-m4.dts (I'm not sure if this file is being used in the final DTB)

https://gist.github.com/neuberfran/701edbe903291799e00a0330c299c799

and
local.conf

https://gist.github.com/neuberfran/b1e0e8de6f47c52bdf255676caf64c62

I stay trying solution based on this site: https://community.element14.com/products/devtools/single-board-computers/warp7/f/forum/30463/linux-dtb-support-to-run-cortex-a7-and-cortex-m4-simultaneously-on-warp-7

User griff0417 tells to include "imx7d-pico-pi-m4.dts". Ok. I include but baseboard_pico_pi.dtsi have issue:

https://gist.github.com/neuberfran/77c2194f2221a1d9196fa14423979124

issue is:
(I don't see anything wrong with line 52.)
| Error: /home/neuberfran/projects/tn-imx-yocto/build-fsl-imx-xwayland-pico-imx7/tmp/work-shared/pico-imx7/kernel-source/arch/arm/boot/dts/baseboard_pico_pi.dtsi:52.1-18 syntax error:

**Comment by neuberfran** [comment]
@mhanuel26 ?

**Comment by neuberfran** [comment]
https://github.com/TechNexion/freertos-tn/tree/freertos_1.0.1_imx7d

**Comment by mhanuel26** [comment]
@neuberfran Sorry but I have not work on that imx7d-pico in years, try to contact NXP. Best of luck!

**Comment by patusaembedded** [comment]
@mhanuel26

I've already contacted NXP :
https://community.nxp.com/t5/NXP-Designs/Reading-file-would-overwrite-reserved-memory-Failed-to-load/m-p/1406740#M954

 and they've resolved most of the issue:
https://stackoverflow.com/questions/71011872/device-tree-error-unable-to-parse-input-tree-syntx-error

I must tell you that your answer was useless and didn't add anything

**Comment by neuberfran** [comment]
@mhanuel26

I've already contacted NXP :
https://community.nxp.com/t5/NXP-Designs/Reading-file-would-overwrite-reserved-memory-Failed-to-load/m-p/1406740#M954

 and they've resolved most of the issue:
https://stackoverflow.com/questions/71011872/device-tree-error-unable-to-parse-input-tree-syntx-error

I must tell you that your answer was useless and didn't add anything
